# Generated by Django 3.2 on 2023-09-05 02:29

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields
import phonenumber_field.modelfields
import services.uploader


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Additional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Təchizat',
                'verbose_name_plural': 'Əlavə təchizatlar',
            },
        ),
        migrations.CreateModel(
            name='BanType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Ban növü',
                'verbose_name_plural': 'Ban növləri',
            },
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField(choices=[(1950, 1950), (1951, 1951), (1952, 1952), (1953, 1953), (1954, 1954), (1955, 1955), (1956, 1956), (1957, 1957), (1958, 1958), (1959, 1959), (1960, 1960), (1961, 1961), (1962, 1962), (1963, 1963), (1964, 1964), (1965, 1965), (1966, 1966), (1967, 1967), (1968, 1968), (1969, 1969), (1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)])),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('engine', models.FloatField(choices=[(0, 0), (0.05, 50), (0.1, 100), (0.15, 150), (0.2, 200), (0.25, 250), (0.3, 300), (0.35, 350), (0.4, 400), (0.45, 450), (0.5, 500), (0.6, 600), (0.7, 700), (0.8, 800), (0.9, 900), (1.0, 1000), (1.1, 1100), (1.2, 1200), (1.3, 1300), (1.4, 1400), (1.5, 1500), (1.6, 1600), (1.7, 1700), (1.8, 1800), (1.9, 1900), (2.0, 2000), (2.1, 2100), (2.2, 2200), (2.3, 2300), (2.4, 2400), (2.5, 2500), (2.6, 2600), (2.7, 2700), (2.8, 2800), (2.9, 2900), (3.0, 3000), (3.1, 3100), (3.3, 3200), (3.3, 3300), (3.4, 3400), (3.5, 3500), (3.6, 3600), (3.7, 3700), (3.8, 3800), (3.9, 3900), (4.0, 4000), (4.1, 4100), (4.2, 4200), (4.3, 4300), (4.4, 4400), (4.5, 4500), (4.6, 4600), (4.7, 4700), (4.8, 4800), (4.9, 4900), (5.0, 5000), (5.1, 5100), (5.2, 5200), (5.3, 5300), (5.4, 5400), (5.5, 5500), (5.6, 5600), (5.7, 5700), (5.8, 5800), (5.9, 5900), (6.0, 6000), (6.1, 6100), (6.2, 6200), (6.3, 6300), (6.4, 6400), (6.5, 6500), (7.0, 7000), (7.5, 7500), (8.0, 8000), (8.5, 8500), (9.0, 9000), (9.5, 9500), (10.0, 10000), (11.0, 11000), (12.0, 12000), (13.0, 13000), (14.0, 14000), (15.0, 15000), (16.0, 16000)])),
                ('transmitter', models.CharField(choices=[('Ön', 'Ön'), ('Arxa', 'Arxa'), ('Tam', 'Tam')], max_length=30)),
                ('seats_count', models.PositiveIntegerField()),
                ('with_driver', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Deactive', 'Deactive')], default='Active', max_length=30)),
                ('code', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('price_to_day', models.FloatField()),
                ('price_to_week', models.FloatField()),
                ('price_to_month', models.FloatField()),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('additional', models.ManyToManyField(blank=True, to='Cars.Additional')),
                ('bantype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cars.bantype')),
            ],
            options={
                'verbose_name': 'Maşın',
                'verbose_name_plural': 'Maşınlar',
            },
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Rəng',
                'verbose_name_plural': 'Rənglər',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Muraciet',
                'verbose_name_plural': 'Muracietler',
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=200)),
                ('answer', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Sual',
                'verbose_name_plural': 'Tez-tez verilən suallar',
            },
        ),
        migrations.CreateModel(
            name='FastOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=100)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='AZ')),
                ('pickup_location', models.CharField(blank=True, choices=[('Heyder Aliyev Beynelxalq Airoportu', 'Heyder Aliyev Beynelxalq Airoportu'), ('İcarə məntəqəsi', 'İcarə məntəqəsi')], default='İcarə məntəqəsi', max_length=100, null=True)),
                ('pickup_date', models.CharField(max_length=100)),
                ('driver_license', models.CharField(max_length=30)),
                ('code', models.SlugField(editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Sifariş',
                'verbose_name_plural': 'Sürətli sifarişlər',
            },
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Yanacaq',
                'verbose_name_plural': 'Yanacaq növləri',
            },
        ),
        migrations.CreateModel(
            name='GearBoxs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Sürətlər qutusu',
                'verbose_name_plural': 'Sürətlər qutusu',
            },
        ),
        migrations.CreateModel(
            name='OrderCancel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=100)),
                ('order_code', models.CharField(max_length=30)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('Gözləmədə', 'Gözləmədə'), ('Yanlış məlumat', 'Yanlış məlumat'), ('Təsdiq edilib', 'Təsdiq edilib')], default='Gözləmədə', max_length=70)),
            ],
            options={
                'verbose_name': 'Sifariş',
                'verbose_name_plural': 'Ləğv ediləcək sifarişlər',
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month_count', models.PositiveIntegerField()),
                ('cars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cars.cars')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('salary', models.FloatField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('Part Time', 'Part Time'), ('Tam ştat', 'Tam ştat'), ('Növbəli', 'Növbəli')], max_length=30, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vacancies/')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Deactive', 'Deactive')], default='Active', max_length=100)),
                ('obligations', ckeditor.fields.RichTextField()),
                ('requirments', ckeditor.fields.RichTextField()),
                ('working_conditions', models.CharField(max_length=100)),
                ('view_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Vakansiya',
                'verbose_name_plural': 'Vakansiyalar',
            },
        ),
        migrations.CreateModel(
            name='VacancyMuraciet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fullname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='AZ')),
                ('description', models.TextField(blank=True, null=True)),
                ('cv', models.FileField(blank=True, null=True, upload_to='vakansiyalar/')),
                ('vacancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cars.vacancies')),
            ],
            options={
                'verbose_name': 'Müraciət',
                'verbose_name_plural': 'Vakansiya müraciətləri',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cars_item', models.ManyToManyField(blank=True, to='Cars.OrderItems')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, null=True, upload_to=services.uploader.Uploader.upload_logo_category)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='Cars.category')),
            ],
            options={
                'verbose_name': 'Kateqoriya',
                'verbose_name_plural': 'Kateqoriyalar',
            },
        ),
        migrations.CreateModel(
            name='CarsOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=200)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='AZ')),
                ('email', models.EmailField(max_length=254)),
                ('pickup_location', models.CharField(choices=[('Heyder Aliyev Beynelxalq Airoportu', 'Heyder Aliyev Beynelxalq Airoportu'), ('İcarə məntəqəsi', 'İcarə məntəqəsi')], default='İcarə məntəqəsi', max_length=100)),
                ('passport_series', models.CharField(max_length=50)),
                ('driving_license_category', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('BC', 'BC'), ('BE', 'BE'), ('C', 'C'), ('CE', 'CE'), ('D', 'D'), ('DE', 'DE')], max_length=30, null=True)),
                ('pickup_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('drop_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('code', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('with_driver', models.CharField(choices=[('True', 'Bəli'), ('False', 'Xeyir')], default='False', max_length=30)),
                ('status', models.CharField(choices=[('Gözləmədə', 'Gözləmədə'), ('Yanlış məlumat', 'Yanlış məlumat'), ('Təsdiq edilib', 'Təsdiq edilib')], default='Gözləmədə', max_length=50)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cars.cars')),
            ],
            options={
                'verbose_name': 'Sifariş',
                'verbose_name_plural': 'Sifarişlər',
            },
        ),
        migrations.CreateModel(
            name='CarsImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to=services.uploader.Uploader.upload_image_cars)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cars.cars')),
            ],
            options={
                'verbose_name': 'Şəkil',
                'verbose_name_plural': 'Maşınlar şəkil',
            },
        ),
        migrations.AddField(
            model_name='cars',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cars.colors'),
        ),
        migrations.AddField(
            model_name='cars',
            name='fuel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cars.fuel'),
        ),
        migrations.AddField(
            model_name='cars',
            name='gearbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cars.gearboxs'),
        ),
        migrations.AddField(
            model_name='cars',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cars.category'),
        ),
        migrations.AddField(
            model_name='cars',
            name='pricing_list',
            field=models.ManyToManyField(blank=True, editable=False, related_name='pricing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cars',
            name='wishlist',
            field=models.ManyToManyField(blank=True, editable=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
